export const USER_TWEETS_FETCHED = "USER_TWEETS_FETCHED";
export const LIKED_TWEETS_FETCHED = "LIKED_TWEETS_FETCHED";
export const CHECKBOX_CLICKED = "CHECKBOX_CLICKED";
export const SEARCH_STRING_CHANGED = "SEARCH_STRING_CHANGED";
export const TWEETS_FETCH_ERROR = "TWEETS_FETCH_ERROR";
